services:
  api:
      build: 
        context: ./docker/api
      ports:
        - "3000:3000"
      env_file:
        - variables.env
  nginx:
      build: 
        context: ./docker/nginx
      ports: 
        - "80:80"
      
  mariadb:
      image: mariadb:latest
      build: 
        context: ./docker/db
      restart: unless-stopped
      env_file:
        - variables.env
  